### ISSUE TITLE
Constraint_Error in gnatcoll_db2ada (gnatcoll-sql-inspect.adb:190:18)

### ISSUE THREAD

**Issue by OCTAGRAM** [AdaCore/gnatcoll-db#5]
Hello! Trying to make first steps with ORM, and still cannot make code generator work. Updated everything, but nothing helps. Unhandled null access dereferencing happens.

Updated environment: Linux x86_64, GNAT 2017 GPL, XMLAda from Git, libgpr from Git, GNATCOLL from Git.

Schema.txt:
`| TABLE                         | Comm_Watch_Items     | Comm_Watch_Item     || Snapshots of known items                             |
| Comm_Watch_Item_Id            | AUTOINCREMENT        | PK                  || Auto-generated id                                    |
| Id_On_Service                 | INTEGER              | NOT NULL            || Integer id as written in URLs and JSON               |
| Id_Character_On_Service       | CHARACTER(1)         | NOT NULL            || Character part of id as written in URLs              |
| JSON_In_The_List              | TEXT                 | NULL                || JSON snapshot as appearing in the list               |
| Date_In_The_List              | TIMESTAMP            | NULL                || Time stamp of JSON snapshot as appearing in the list |
| JSON_Alone                    | TEXT                 | NULL                || JSON snapshot if opened alone (usually more rich)    |
| Date_Alone                    | TIMESTAMP            | NULL                || Time stamp of JSON snapshot if opened alone          |
| UNIQUE: | Id_On_Service, Id_Character_On_Service | Full_Id_On_Service |

| TABLE                         | Comm_Watch_Bookmarks | Comm_Watch_Bookmark || Bookmark one-to-many relation (username-to-bookmark) |
| Comm_Watch_Bookmark_Id        | AUTOINCREMENT        | PK                  || Auto-generated id                                    |
| Username                      | TEXT                 | NOT NULL            || Username                                             |
| Bookmark_Id_On_Service        | INTEGER              | NOT NULL            || Integer bookmark id as written in URLs and JSON      |
| Bookmark_Character_On_Service | CHARACTER(1)         | NOT NULL            || Character part of bookmark id as written in URLs     |
| FK: | Comm_Watch_Items | Bookmark_Id_On_Service, Bookmark_Character_On_Service | Id_On_Service, Id_Character_On_Service |
| UNIQUE: | Username, Bookmark_Id_On_Service, Bookmark_Character_On_Service | Username_Bookmark |`

`gnatcoll_db2ada -api Comm_Watch.Database -orm Comm_Watch.ORM -dbmodel Schema.txt`

The problem disappears if I remove foreign key, but that destroys the whole point of ORM. I look at this line and cannot see anything wrong with it. All according to the documentation.

**Comment by briot** [comment]
Hi,

I tested your schema.txt with a patched version of gnatcoll_db2ada I have locally (I am
planning on submitting the patches, but I have a lot o them).

First it reports several errors similar to:
     schema.txt:5 Unknown property “NULL"

(this was accepted in AdaCore’s version, but does nothing).
Removing them, I now also get an “access check failed”.

Taking a closer look at your schema, the foreign key is kind of surprising, since it doesn’t
reference a primary key in Comm_Watch_Items. Shouldn’t Id_On_Service be part of the
foreign key there ?
The bug is still there after that change though.

Then I realized I also patched the documentation, which was incorrect. The Foreign Key
line should be:

     | FK: | Comm_Watch_Items | Bookmark_Id_On_Service  Bookmark_Character_On_Service | Id_On_Service  Id_Character_On_Service |

with space as separator, not comma (don’t ask why, I forgot why it was done that way 15 years ago).

Now I can generate the Ada API, though I still get an error with “-orm”.
And finally, I found out this is because I had two spaces between the name of the keys.
So conclusion:

works if your foreign key line is:

| FK: | Comm_Watch_Items | Bookmark_Id_On_Service Bookmark_Character_On_Service | Id_On_Service Id_Character_On_Service |



I’ll try and submit my patches at some point

Emmanuel

**Comment by OCTAGRAM** [comment]
I confirm that code generator finishes without errors if I remove commas in FK.

> Taking a closer look at your schema, the foreign key is kind of surprising, since it doesn’t reference a primary key in Comm_Watch_Items. Shouldn’t Id_On_Service be part of the foreign key there ?

If database is primary, then yes, but database is now a mirror to already established JSON-on-filesystem store. I have read that several database engines have to physically shift items if new record with not greatest primary key being inserted. So I let database have another primary key.

What about UNIQUE and INDEX? They seem to work with commas. Should I rewrite them with spaces?

**Comment by OCTAGRAM** [comment]
The code produced by tools does not compile.

``
   function Comm_Watch_Items
     (Self : Detached_Comm_Watch_Bookmark)
     return Detached_Comm_Watch_Item'Class
   is
      …
         D.ORM_FK_Comm_Watch_Items := new Detached_Comm_Watch_Item'Class'
           (Get_Comm_Watch_Item (S, Id_On_Service => D.ORM_Bookmark_Id_On_Service,Id_Character_On_Service => To_String (D.ORM_Bookmark_Character_On_Service)));
``

This function seemingly generates foreign key reference, but there is no matching Get_Comm_Watch_Item with appropriate signature. So it is currently not possible to handle this, right?

The database is about to process lots of requests like WHERE Username = Text_Param (1) and ((Bookmark_Id_On_Service = Integer_Param (2) and Bookmark_Character_On_Service = Text_Param (3)) or (… and …) or … repeat 30 times). It defines the structure.
